rm -rf build
cd python

set SKBUILD_CMAKE_DEFINE=TRACY_DELAYED_INIT=ON;CMAKE_POSITION_INDEPENDENT_CODE=ON;DOWNLOAD_CAPSTONE=FALSE;NO_ISA_EXTENSIONS=ON

%PYTHON% -m pip install --no-deps --no-build-isolation -vv .
